### PR TITLE
Fixes #3 

### LINKED ISSUE #3: config.json can be downloaded from the web and expose db credentials
config.json file should be put in another folder (not reachable from the web but available to PHP and python script for reading) or protected somehow, otherwise it could be downloaded from the web and expose db credentials and other sensitive configuration parameters.

### PR DESCRIPTION
**Pull request by mauntrelio**
Protects . files in web apache folder via .htaccess, changes config.json to .config.json

### CODE REVIEW

**Review by paskino — COMMENTED** [review]
does it apply also to carb_api.php? and carb_query.php? They seem to load config.json

**Comment by mauntrelio** [comment]
No, the only php file which read from .config.json is config.php, which is included from carb_api.php and carb_query.php

**Comment by paskino** [comment]
I guess my question is: 
Do I have to change carb_query.php and carb_api.php to make them load .config.json?

**Comment by mauntrelio** [comment]
I guess my answer was:
No, the only php file which read from .config.json is config.php, which is included from carb_api.php and carb_query.php

**Comment by mauntrelio** [comment]
BTW, of course on the live site you would need to change, but I would say you should re-deploy the whole application, because the current .htaccess file is screwed up...

**Pull request merged**
